### ISSUE TITLE
Rename all Page Shots to [Firefox] Screenshots

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots-loadtests#21]
We should do this before migrating this repo into the **mozilla-services** org.

**Comment by pdehaan** [comment]
I'll need @karlht or @stuartphilp or maybe @tarekziade to bump me up to admin on this repo or something. Since moving this into **mozilla-services** control, I seem to have lost the ability to edit the repo's description. I shoulda renamed things before migrating, but #yolo.

**Comment by karlht** [comment]
I lack the powers to do this, alas.
