### ISSUE TITLE
Add handler for empty env var

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/screenshots-loadtests#32]
molotov can convert empty env var strings in a statement like `os.getenv(some_string, 0)`, but Docker seems to choke on this, unable to convert empty string to default of 0.

perhaps we should use something like this:

```py
MY_CONST = 0 if not my_const.isdigit() else int(my_const)
```

**Comment by pdehaan** [comment]
Did a bit of local testing last night and this may also do the trick:

```py
import os

MY_CONST = int(os.getenv('MY_CONST') or '0')

print(MY_CONST)
```

```sh
$ python env-test.py # 0
$ MY_CONST= python env-test.py # 0
$ MY_CONST='' python env-test.py # 0
$ MY_CONST=99 python env-test.py # 99
```
