### ISSUE TITLE
Add new ardere.json config file

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/screenshots-loadtests#43]

**Comment by pdehaan** [comment]
@rpappalax: we have a current placeholdery one at [/ardere.json](https://github.com/mozilla-services/screenshots-loadtests/blob/master/ardere.json).

**Comment by rpappalax** [comment]
need to update this file with a few tweaks for ardere changes and add in the other necessary env vars (WEIGHT_CREATE_SHOT, etc.).
